# fly.toml app configuration file generated for booklist-api on 2023-10-31T23:03:06-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "collectit-webapi"
primary_region = "gru"

[build] 
  
[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
